### PR TITLE
Integrate Travis CI

### PR DESCRIPTION
**Pull request by paulmenzel**
It’s good practice to test each commit and merge/pull request before accepting it into the master branch.

[Travis CI](https://travis-ci.org/) offers such a service, and integrates well with GitHub. After creating an
account, that account can be associated with a GitHub account, and build testing can then be enabled
for a project.

Then, if a file `.travis.yml` is present in the top level directory of the project, Travis CI will execute the
configured commands, and annotates a merge/pull request, if all commands succeed or fail.

This merge/pull request adds the configuration file for Travis CI.

### CODE REVIEW

**Comment by paulmenzel** [comment]
My fork is already associated with Travis CI, so [here](https://travis-ci.org/paulmenzel/cups/builds/274645677?utm_source=github_status&utm_medium=notification) is the current status.

**Comment by paulmenzel** [comment]
I removed the macOS builds with GCC from Homebrew from the build matrix, as this currently fails. The latest upload passes all items from the build matrix.

**Comment by michaelrsweet** [comment]
Sorry, we are not using Travis for CUPS development, we have our own internal solution. And as for making macOS builds work with third-party compilers, that is simply not something we will support.

**Comment by paulmenzel** [comment]
Just a note, that this was added in October 2018 in commit https://github.com/apple/cups/commit/d65e20fe7c5b192522ba01865bfcbd3dbc0e448e (Add Travis CI support.). Maybe it should be backported to the 2.2.x branch.

**Comment by michaelrsweet** [comment]
@paulmenzel I may have added a Travis config file, but I am unable to grant it privileges to an Apple repository so it will be going away... :(

**Comment by paulmenzel** [comment]
On 02/25/19 05:07, Michael R Sweet wrote:
> @paulmenzel I may have added a Travis config file, but I am unable to
> grant it privileges to an Apple repository so it will be going
> away... :(

Did you contact the Travis CI folks?

**Comment by michaelrsweet** [comment]
@paulmenzel It is not a Travis CI thing, it is an organizational thing at Apple (who needs to grant the access to Travis CI).

**Pull request closed without merging**
