### PR TITLE
added html tag LABEL to inputs of type CHECKBOX and RADIO

### PR DESCRIPTION
**Pull request by gpunktschmitz**

### CODE REVIEW

**Comment by michaelrsweet** [comment]
@gpunktschmitz Is there a specific reason for this addition?

**Comment by gpunktschmitz** [comment]
@michaelrsweet it makes the administration/web interface more convenient/easier to use.

**Comment by michaelrsweet** [comment]
@gpunktschmitz *How* does it make the web interface more convenient/easier to use?

(doesn't look/work any different for me)

**Comment by gpunktschmitz** [comment]
@michaelrsweet you may now click on the text (label) to activate the checkbox.

**Comment by michaelrsweet** [comment]
@gpunktschmitz I just tried this with Safari, Firefox, and Chrome (all up-to-date) and *none* of them allowed me to just click on the label text to toggle the check boxes or radio buttons.

What platform/browser are you seeing this on?

**Comment by gpunktschmitz** [comment]
@michaelrsweet I'm running Firefox/Linux Mint 18.2 - as this is basic HTML4 [it should work](http://caniuse.com/#search=label) on all browsers/plattforms. Just to double-check: when you go to the admin-page you cannot click on the the server settings text to activate the checkbox? if not - can you provide me with the source view of the admin-page?

**Comment by michaelrsweet** [comment]
Never mind, when I copied one of the changes the "id" for the checkbox didn't make it over correctly. Once I had the right id attribute it started working...

Will queue this up for CUPS 2.3...

**Pull request merged**
