### PR TITLE
Fix not-working cupsSNMPSupplies and cupsIPPSupplies settings via lpa…

### PR DESCRIPTION
**Pull request by zdohnal**
…dmin

Connected to issue #5609

### CODE REVIEW

**Comment by michaelrsweet** [comment]
Looks about right, will need to merge by hand however...

**Comment by zdohnal** [comment]
Oh, I missed the indentation - I hope I corrected it now, please correct me if I'm wrong.

**Comment by michaelrsweet** [comment]
Indentation looks fine, I just can't merge to multiple Git branches via pull requests. No biggy, this is a small change...

**Comment by michaelrsweet** [comment]
Oh, and there were two other places where we needed to set ppdchanged to 1...

[master 9539c5306] Fix lpadmin with cupsIPPSupplies and cupsSNMPSupplies (Issue #5610)

[branch-2.2 c50773934] Fix lpadmin with cupsIPPSupplies and cupsSNMPSupplies (Issue #5610)

**Comment by zdohnal** [comment]
> Indentation looks fine, I just can't merge to multiple Git branches via pull requests. No biggy, this is a small change...

Can I do anything about it in the future?



> Oh, and there were two other places where we needed to set ppdchanged to 1...
> 

D'oh, I missed those two, thank you for checking!

> [master [9539c53](https://github.com/apple/cups/commit/9539c53065170e97836503074e770d7b5fbf9f83)] Fix lpadmin with cupsIPPSupplies and cupsSNMPSupplies (Issue #5610)
> 
> [branch-2.2 c50773934] Fix lpadmin with cupsIPPSupplies and cupsSNMPSupplies (Issue #5610)

Thank you for the fix!

**Comment by michaelrsweet** [comment]
@zdohnal Unfortunately, Github is all about merging to master. Until they add support for pull requests against alternate branches I'll just keep doing manual merges...

Most of these fixes are pretty small anythings, so it is no problem - the bulk of the work has already been done! :)

**Pull request closed without merging**
