### PR TITLE
insert explicit casts to calm compiler warnings for -Wsign-conversion

### PR DESCRIPTION
**Pull request by mpsuzuki**
During compilation of the latest source, I received several warnings for -WSign-conversion. Here is a patch inserting explicit casts to calm them.

### CODE REVIEW

**Comment by michaelrsweet** [comment]
Sigh...  This is all because the newest GCC defaults to unsigned enums... Will consider for 2.3.x.

**Comment by mpsuzuki** [comment]
I see. How about add "-Wno-sign-conversion" to CFLAGS as quick workaround?

**Comment by michaelrsweet** [comment]
@mpsuzuki The problem with -Wno-sign-conversion is that it also eliminates valid issues, like between size_t and ssize_t, that we want to see reported.

**Comment by michaelrsweet** [comment]
Merged mostly as-is...

[master 8ef4f507d] Eliminate new GCC compiler warnings (Issue #5591)

**Pull request closed without merging**
