### PR TITLE
Localization for job's and printer's status messages and messages in cupsdAddEvent()

### PR DESCRIPTION
**Pull request by dimv36**
Those patch add localization for messages in cupsdAddEvent() and localization for status of printers and jobs.

### CODE REVIEW

**Comment by dimv36** [comment]
Sorry, those patch add only translation possibility of those messages, but not translation at all.

**Comment by dimv36** [comment]
This commit adds localization support in functions cupsdAddEvent() & cupsdSetJobState()

**Comment by michaelrsweet** [comment]
OK, so as-is this patch is not usable.

One of the reasons we have not localized the notification text in cupsd is that the subscriber's natural language can be different than the system-wide default language. Doing this properly requires localizing the event multiple times (once for each subscription).

**Comment by michaelrsweet** [comment]
Also, the cupsNotifyGetSubject and cupsNotifyGetText functions in libcups localize notifications on the client-side (independent of the subscription language)

**Comment by michaelrsweet** [comment]
Sorry, not accepting this PR...

**Pull request closed without merging**
