### PR TITLE
Create untranslated cups_da.po

### PR DESCRIPTION
**Pull request by scootergrisen**
It seems translated files (templates etc.) is only included in CUPS packages for distributions if a po file exists for that language.
So i create this untranslated cups_da.po file and hope danish translation will be included.

### CODE REVIEW

**Comment by michaelrsweet** [comment]
Sorry, until we have a significant number of translated strings we can't include it...

**Comment by scootergrisen** [comment]
How many is "significant number"?

**Comment by michaelrsweet** [comment]
We'd want many of the printer-state-reasons keywords (marker-xxx, media-xxx, and toner-xxx are the most common) along with the messages from the common print commands (cancel, lp, lpadmin, lpc, lpoptions, lpq, lpr, lpstat) covered, at least.

**Comment by scootergrisen** [comment]
It seems no language have translated marker-*, media-* and toner-*.
Expect "en" but that's the source language.

And its not always clear what the source string is/what i should translate.
So i think it would be better to fix this before asking people to translate it.
If i translate it now and the following problem is fixed i will have to translate it once again.

If cups_da.po says:

> #. TRANSLATORS: Marker Opc Missing
> msgid "printer-state-reasons.marker-opc-missing"
> msgstr ""

First of all the string i should translate should be in msgid.
But ok i look at the comment instead and use "Marker Opc Missing" as the source string.

But then if i look in cups_en.po the string that is suppose to be the source string is not the same.
Its "OPC missing" not "Marker Opc Missing" like the comment says.

> #. TRANSLATORS: Marker Opc Missing
> msgid "printer-state-reasons.marker-opc-missing"
> msgstr "OPC missing"

**Comment by scootergrisen** [comment]
I made https://github.com/apple/cups/pull/5707 instead.

**Pull request closed without merging**
