### PR TITLE
snmp page counting is unreliable - give way to disable it in PPD file

### PR DESCRIPTION
**Pull request by zdohnal**
Hi Mike,

our customer found out that snmp page counting is unreliable for some printers (printers seems to send end of printing before life counter in printer snmp agent got updated - this behavior resulted in bad page count in cups web ui), so we implemented the way to turn off page counting by snmp. User simply add "cupsSNMPPages: False" into printer ppd file and cups then uses counting by 'PAGE X 1' messages.
I understand CUPS project is on its way to drop .ppd functionality, but IMHO it is good to offer opportunity for these, which still uses ppd files and they complain about snmp page counting, until better solution is implemented.

### CODE REVIEW

**Comment by michaelrsweet** [comment]
@zdohnal How is this different from the *cupsSNMPSupplies keyword that does the same thing (plus supply level information)?

I really don't want to add yet another switch for controlling a legacy protocol.

**Comment by zdohnal** [comment]
It only switches off SNMP page counting - supply level info is still shipped by SNMP.

**Comment by michaelrsweet** [comment]
Still not convinced, but will hold this possibly for a future release.

**Comment by zdohnal** [comment]
I can possibly rewrite it into similar way as cupsSNMPSupplies are applied - like command line option, if it helps. But it didn't look like as such serious issue with high impact to have extra command line option - but sure, it will look better if it can be set by command line. Is it acceptable?

**Comment by michaelrsweet** [comment]
OK, the changes for issue #4991 should mitigate the issues associated with lowball accounting numbers - we now use MAX(printer-page-count,filter-page-count) when reporting the number of pages that were printed.

**Comment by michaelrsweet** [comment]
OK, I'm punting on this pull request since our future focus will be on modern protocols...

**Pull request closed without merging**
