### PR TITLE
--enable-debug-printfs bugfix + other cosmetic fixes

### PR DESCRIPTION
**Pull request by computersforpeace**
Addresses these:

https://github.com/apple/cups/issues/4784
http://www.cups.org/pipermail/cups/2016-March/027577.html

I hope you're taking Github PRs now?

Regards,
Brian

### CODE REVIEW

**Comment by michaelrsweet** [comment]
Yes, we'll be accepting PRs, but please be patient as I am currently swamped making this Github thing happen... :)

**Comment by michaelrsweet** [comment]
The poppler/ghostscript changes were addressed separately.

Fixed debug_ops.

[master 508de67] The debug strings table for mime type operations was out of sync with the enumeration (PR #4787)
[branch-2.1 f94124c] Mirror fix from master.

I'm undecided on whether I'll add the vim swap file change to .gitignore; that's something you can handle locally in the meantime...

**Comment by computersforpeace** [comment]
Did you have any comments on this part of my original question?

> It'd be best if we could use the compiler to our advantage to catch
these types of errors (e.g., introduce some kind of compile-time
assertion;, or use a switch/case without a 'default' instead of an
array, since many compilers would warn about the unused enum), but I
didn't really want to refactor this all for a bugfix. I'm also not as
familiar with the non-Linux systems that CUPS is built for, so I'm not
sure what (if any) C99 features I could use, for instance.

I notice you didn't even take my comment for the enum:

    /* NOTE: update debug_ops[] in type.c whenever editing this enum */

so it seems this is just as liable to get broken again in the future.

**Comment by michaelrsweet** [comment]
mime.h is a public header so I don't want to expose internal implementation details there (probably just confuse anyone reading the header).

But regardless, we've added 2 new operations to the enum over the last 18 years so I'm not particularly worried about it.

**Pull request closed without merging**
