### PR TITLE
Add device ID for Dymo LabelWriter 400

### PR DESCRIPTION
**Pull request by zdohnal**
SSIA

### CODE REVIEW

**Comment by michaelrsweet** [comment]
There are other printers this driver works with, so I'm not sure I want to tie this driver to it...

Is there a reason you need this?

**Comment by zdohnal** [comment]
I'm sorry, you're right - I made a mistake - I reviewed the patch badly, setting the ppd for only LabelWriter is not okay...
About the reason: Once there was Fedora user, who had a problem with installing his Dymo LabelWriter 400 - he got a bad ppd file and Tim fixed it by the patch above. There is the report https://bugzilla.redhat.com/show_bug.cgi?id=747866 . Dymo LabelWriter 400 doesn't have any support in foomatic or gutenprint and cups dymo ppd worked for user.
Is it acceptable to have another ppd in CUPS for LabelWriter (see updated patch) or should I pursue this issue in f.e. foomatic, because ppds are going away?

**Comment by zdohnal** [comment]
@michaelrsweet ok, I understood the printer driver projects will stay, because printer applications (ipp server + printer driver project such Gutenprint/Foomatic) can have use for them when managing old legacy printers, which don't support IPP everywhere...
Is there a way in .drv file to tell: "Please use this ppd with this printer too"? I was unable to find such way... if there is not, we can close the pull request.

**Comment by michaelrsweet** [comment]
@zdohnal Printer driver projects, yes, but I'm (perhaps too optimistically) hoping that Foomatic will no longer be needed.

The 1284DeviceID and NickName strings are the ones used for driver matching. We aren't technically adding another driver here, but historically we haven't provided printer-specific values. Maybe we can do something with the MFG and CMD values so we match any Dymo printer?

**Comment by zdohnal** [comment]
I didn't forget about this issue - I'll get into it in near future, I hope :(

**Pull request closed without merging**
