### PR TITLE
Add Upstart socket activation support

### PR DESCRIPTION
**Pull request by computersforpeace**
I took this as a reference:

https://bugs.launchpad.net/upstart/+bug/1276713

But rewrote major chunks of it, to rebase onto the latest CUPS, fix bugs, clean up junk, make upstart support configurable, and refactor the general "on demand" code, so I didn't have to duplicate it yet again.

Tested on Chromium OS.

I will try to figure out how to CC Till, but I don't know GitHub that well.

### CODE REVIEW

**Comment by computersforpeace** [comment]
@tillkamppeter FYI

**Comment by michaelrsweet** [comment]
We'll need a signed contributor's agreement for this one...  Details here:

https://github.com/apple/cups/blob/master/CONTRIBUTING.md

and:

https://www.cups.org/AppleContributorAgreement_2011-03-10.pdf

**Comment by tillkamppeter** [comment]
@computersforpeace: Great, thank you for working on getting this upstream.

**Comment by computersforpeace** [comment]
FYI, I emailed the contributor's agreement last week. Let me know if you have problems with either the CLA or the code.

**Comment by michaelrsweet** [comment]
OK, legal has approved everything so I'll be merging this for the next 2.2 beta...

**Comment by michaelrsweet** [comment]
Also see follow up commit with some cleanup:

[master 1166bf5] Do some cleanup for the on-demand support - remove old launchd support (no longer needed), naming/style updates, fix compiler warnings.

**Pull request merged**
