### PR TITLE
Proposed patch for issue #5135

### PR DESCRIPTION
**Pull request by zdohnal**
More info in issue #5135

### CODE REVIEW

**Comment by zdohnal** [comment]
Only other thing to do is create something like cupsEnumDests2(), which is used for non default http connection - but it will need to extract code from cupsEnumDests(), where http needs to be used and then call cupsEnumDests(), but I do not see any simple way how to do it. For now I use duplicate of cupsEnumDests, which uses http.

**Comment by michaelrsweet** [comment]
We won't change public API in a way that breaks source or binary compatibility, and we have no plans of updating cupsEnumDests to take a http_t pointer argument since the use of remote CUPS servers has been deprecated for a long time due to incompatibilities with sandboxing on macOS and the various security features on the different Linux distros.

**Comment by zdohnal** [comment]
If I create the patch without breaking public API, would it be acceptable?

**Comment by michaelrsweet** [comment]
We will come up with a patch shortly. Please be patient.

**Comment by zdohnal** [comment]
I am sorry, I didn't want to sound impatient, I just wanted to help you with solution (I have patch without breaking public API now, I can create pull request anytime). To sum it up, I apologize.

**Pull request closed without merging**
