### PR TITLE
A few string corrections

### PR DESCRIPTION
**Pull request by scootergrisen**

### CODE REVIEW

**Comment by scootergrisen** [comment]
How do i remove "Fix po headers (Language-Team and Language)" from this pull request?

**Comment by michaelrsweet** [comment]
@scootergrisen Not sure. But I can just manually merge the string corrections...

**Comment by scootergrisen** [comment]
Maybe i just undid what you did.
I dont know.

**Comment by michaelrsweet** [comment]
[master fa2851d5b] Update Danish localization (Issue #5504)

**Pull request closed without merging**
